server:
  port: 8189
  servlet:
    context-path: /api/v1/app
#  servlet:
#    session:
#      timeout: 60s


spring:
  datasource:
    sslmode: require
    url: jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/deug7fqhj7ivna
    username: ansfxthwyxcuig
    password: d007adeabf6f2ce50f794f85bd2fcd10539892ec1b5fa8ef48b79779d21918b6
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
      use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 400MB
      max-request-size: 600MB
  flyway:
    sslmode: required
    url: jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/deug7fqhj7ivna

    user: ansfxthwyxcuig
    password: d007adeabf6f2ce50f794f85bd2fcd10539892ec1b5fa8ef48b79779d21918b6

    enabled: true
    locations: classpath:db/migration
#  web:
#    resources:
#      static-locations: classpath:static


